from pathlib import Path
import json, re, sqlite3, subprocess, sys, tempfile, time, urllib.request, urllib.error, os

ROOT = Path(__file__).resolve().parents[1]
checks = []

def check(name, condition, detail=""):
    checks.append((name, bool(condition), detail))
    if not condition:
        print("FAIL:", name, detail)

cfg = (ROOT/"config/runtime-config.js").read_text()
check("Runtime config exists", "apiBaseUrl" in cfg and "propertySlug" in cfg)
check("No Stripe enabled", "stripeEnabled: false" in cfg)
check("No outbound email enabled", "outboundEmailEnabled: false" in cfg)

prop = json.loads((ROOT/"properties/arbor-vista-retreat/property.json").read_text())
check("Property package valid", prop["slug"] == "arbor-vista-retreat")
check("Flexible occupancy retained", prop["maximumRequestedGuests"] == 8)
check("Owner email retained as configuration", prop["ownerNotificationEmail"] == "swasam.venture@gmail.com")

admin = (ROOT/"admin/admin.js").read_text()
check("Admin uses runtime API base", "cfg.apiBaseUrl" in admin)
check("Admin sends property slug", "X-Property-Slug" in admin)
check("Admin has request timeout", "AbortController" in admin)

shared = (ROOT/"assets/script.js").read_text()
check("Booking storage is property scoped", "${cfg.propertySlug}-booking-draft-v2" in shared and "arbor-vista-booking-draft-v2" in shared)
check("Booking API is cloud configurable", "cfg.apiBaseUrl" in shared)

htmls = list(ROOT.rglob("*.html"))
check("All HTML files load runtime config", all("runtime-config.js" in p.read_text(errors="ignore") for p in htmls), f"{len(htmls)} files")

schema = (ROOT/"Backend/schema.sql").read_text()
check("SQLite schema remains property scoped", "property_id TEXT NOT NULL" in schema)
check("Property domains table added", "property_domains" in schema)
check("Property members table added", "property_members" in schema)

pg = (ROOT/"supabase/migrations/001_cloud_multi_property.sql").read_text()
check("PostgreSQL migration included", "create table if not exists properties" in pg.lower())
check("PostgreSQL RLS enabled", "enable row level security" in pg.lower())

server = (ROOT/"Backend/server.py").read_text()
check("Backend uses environment variables", 'os.getenv("PORT"' in server and 'ARBOR_DB_PATH' in server)
check("Versioned API supported", '"/api/v1"' in server)
check("Property resolution implemented", "X-Property-Slug" in server and "resolve_property" in server)
check("Wildcard CORS removed", "Access-Control-Allow-Origin','*'" not in server and 'Access-Control-Allow-Origin", "*"' not in server)

# Syntax compile.
for rel in ["Backend/server.py", "Backend/ical_db.py", "QA/run_v33_cloud_qa.py"]:
    p = ROOT/rel
    result = subprocess.run([sys.executable, "-m", "py_compile", str(p)], capture_output=True, text=True)
    check(f"Python syntax: {rel}", result.returncode == 0, result.stderr)

# Verify package manifest later generated by build step.
print(f"{sum(ok for _,ok,_ in checks)}/{len(checks)} checks passed")
if not all(ok for _,ok,_ in checks):
    raise SystemExit(1)
